{{- range $api := .Values.extraApis }}
{{- if $api.enabled }}
{{- $values := merge (deepCopy $api) (deepCopy $.Values.consentManagerApi) -}}
{{- $context := dict "Values" (merge (deepCopy $values) (dict "global" $.Values.global)) "Chart" $.Chart "Release" $.Release "Files" $.Files "Capabilities" $.Capabilities -}}
{{- with $context }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if (or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector: {{- include "common.labels.matchLabels" (dict "customLabels" .Values.podLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: consent-manager-{{ .Values.nameOverride }}
{{- end }}
{{- end }}
{{- end }}
